#! /bin/sh

# ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
# ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
# ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
# ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
# ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
# ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
# BSPWMRC | Hacker environment
# Enríque González (Aka. Usergh0st)
# Color theme: Simon

# Bspwm monitors for six.
bspc monitor -d I II III IV V VI VII VIII IX X

# Cursor mouse fix,
xrdb -merge ~/.Xresources
xsetroot -cursor_name left_ptr &
xset +dpms
xset dpms 600 600 0
xset s 600

# Bspwm config.
bspc config border_width 1
bspc config focused_border_color \#0b6599
bspc config normal_border_color \#6597a0
bspc config window_gap 5
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config gapless_monocle true
bspc config paddingless_monocle true

# Bspwm rules.
bspc rule -a 'SimpleScreenRecorder' state=floating follow=on
bspc rule -a 'BleachBit' state=floating follow=on
bspc rule -a 'stacer' state=floating follow=on
bspc rule -a 'org.gnome.Nautilus' state=floating follow=on
bspc rule -a 'gnome-calculator' state=floating follow=on
bspc rule -a 'Nitrogen' state=floating follow=on
bspc rule -a 'Synaptic' state=floating follow=on

# Auto-Start

# Starting sxhkd hotkey daemon.
pgrep -x sxhkd >/dev/null || sxhkd &

# Starting picom compositor.
pgrep -x picom >/dev/null || picom &

pgrep -x /usr/libexec/polkit-mate-authentication-agent-1 >/dev/null || /usr/libexec/polkit-mate-authentication-agent-1 &

pgrep -x dunst >/dev/null || dunst &

pgrep -x greenclip >/dev/null || greenclip daemon &

# pgrep xss-lock >/dev/null || xss-lock -- betterlockscreen -l dim &

# Starting polybar.
${HOME}/.config/polybar/launch.sh

# Starting walls script.
${HOME}/.local/bin/restore_wallpaper.sh
